# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ep2Site', '0002_cluster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='users',
        ),
        migrations.DeleteModel(
            name='Cluster',
        ),
    ]
