# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ep2Site', '0005_auto_20160706_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='review',
            old_name='comentario',
            new_name='review',
        ),
    ]
