# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ep2Site', '0006_auto_20160711_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='id',
        ),
        migrations.AlterField(
            model_name='review',
            name='nome_de_usuario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
